=== Vyacheslav-Lapin/javalab-spring/src/test/resources/xml/menu.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://epam.com/spb/javalab/xml/menu"
        xmlns:tns="http://epam.com/spb/javalab/xml/menu"
        elementFormDefault="qualified"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://www.w3.org/2001/XMLSchema http://www.w3.org/2001/XMLSchema.xsd">

    <element name="breakfast-menu">
        <complexType>
            <sequence>
                <element name="food" type="tns:food" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>
    Â 
    <complexType name="food">
        <sequence>
            <element name="name" type="token"/>
            <element name="price" type="token"/>
            <element name="description" type="string"/>
            <element name="calories" type="int"/>
        </sequence>
        <attribute name="id" type="int"/>
    </complexType>
</schema>

=== Vyacheslav-Lapin/javalab-spring/src/test/resources/xml/menu.xml
<?xml version="1.0" encoding="UTF-8"?>
<breakfast-menu
        xmlns="http://epam.com/spb/javalab/xml/menu"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="
            http://epam.com/spb/javalab/xml/menu menu.xsd">
    <food id="1">
        <name>Belgian Waffles</name>
        <price>$5.95</price>
        <description>
            two of our famous Belgian Waffles with plenty of real maple syrup
        </description>
        <calories>650</calories>
    </food>
    <food id="2">
        <name>Strawberry Belgian Waffles</name>
        <price>$7.95</price>
        <description>
            light Belgian waffles covered with strawberrys and whipped cream
        </description>
        <calories>900</calories>
    </food>
</breakfast-menu>
